# Generated by Django 5.2.11 on 2026-02-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
