# Generated by Django 5.2.11 on 2026-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="activity_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pipeline", "Pipeline Builder"),
                    ("choice", "Visual Choice"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
