# Generated by Django 5.2.11 on 2026-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_lesson_activity_json_lesson_activity_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={},
        ),
        migrations.AlterField(
            model_name="lesson",
            name="activity_type",
            field=models.CharField(
                choices=[("none", "None"), ("choice", "Visual Choice")],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
