# Generated by Django 5.2.11 on 2026-02-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_lesson_options_alter_lesson_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("order", "Order Blocks"),
                    ("choice", "Choice Cards"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
