# Generated by Django 5.2.11 on 2026-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_lesson_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
