# Generated by Django 5.2.11 on 2026-02-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_videos"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Videos",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("order", "Order Blocks"),
                    ("choice", "Choice Cards"),
                    ("mouse", "Mouse Practice"),
                    ("typing", "Keyboard Game"),
                    ("tidy", "Tidy the Computer"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
