# Generated by Django 5.2.11 on 2026-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_lesson_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("order", "Order Blocks"),
                    ("choice", "Choice Cards"),
                    ("mouse", "Mouse Practice"),
                    ("typing", "Keyboard Game"),
                    ("tidy", "Tidy the Computer"),
                    ("triple", "3-in-1 Digital Skills"),
                    ("foundations3", "3-in-1: Digital Foundations"),
                    ("files3", "3-in-1: Files & Folders"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
