# Generated by Django 5.2.11 on 2026-02-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_alter_lesson_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.CharField(
                choices=[
                    ("computer_basics", "Computer Basics"),
                    ("systems_logic", "Systems Logic & Critical Thinking"),
                    ("careers", "Careers"),
                ],
                default="computer_basics",
                max_length=40,
            ),
        ),
    ]
