# Generated by Django 5.2.11 on 2026-02-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_alter_lesson_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("order", "Order Blocks"),
                    ("choice", "Choice Cards"),
                    ("mouse", "Mouse Practice"),
                    ("typing", "Keyboard Game"),
                    ("tidy", "Tidy the Computer"),
                    ("triple", "3-in-1 Digital Skills"),
                    ("foundations3", "3-in-1: Digital Foundations"),
                    ("files3", "3-in-1: Files & Folders"),
                    ("word5", "5-in-1: Microsoft Word"),
                    ("excel8", "8-in-1: Excel Basics"),
                    ("ppt10", "10-in-1: Microsoft PowerPoint Playground"),
                    ("cp12", "12-in-1: Control Panel Playground"),
                    ("safety12", "12-in-1: Safety + Good/Not Good"),
                    ("jobs8", "8-in-1: Jobs That Use Computers"),
                    ("logic5", "5-in-1: Logic & Critical Thinking"),
                    ("logic5", "5-in-1: IPO + Decisions + Loops + Data"),
                    ("sys5", "5-in-1: Systems + Memory + Storage"),
                    ("net5", "5-in-1: Internet + Apps + Networks"),
                    ("teams8", "8-in-1: Speed + Safety + Tech Teams"),
                    ("career8", "8-in-1: Engineers + Data Engineers"),
                    ("netcloud8", "8-in-1: Network + Cloud Engineers"),
                    ("cyberai8", "8-in-1: Cybersecurity + AI Engineers"),
                    ("teamtools8", "8-in-1: Teams + Tools Playground"),
                    ("project8", "8-in-1: Projects + Ethics + Paths"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
